name: Nightly Build

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: nightly-build-publish
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build and Publish
        run: ./gradlew publish
        env:
          GITHUB_PUBLISH_USERNAME: ${{secrets.GIT_PUBLISH_USERNAME}}
          GITHUB_PUBLISH_TOKEN: ${{secrets.GIT_PUBLISH_TOKEN}}
